//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HESSLocalDBEntities : DbContext
    {
        public HESSLocalDBEntities()
            : base("name=HESSLocalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EHSSData> EHSSData { get; set; }
        public virtual DbSet<EHSSUser> EHSSUser { get; set; }
        public virtual DbSet<HazardType> HazardType { get; set; }
        public virtual DbSet<MSDSData> MSDSData { get; set; }
        public virtual DbSet<MSDSDetail> MSDSDetail { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
    }
}
