//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HazardType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HazardType()
        {
            this.EHSSData = new HashSet<EHSSData>();
            this.MSDSDetail = new HashSet<MSDSDetail>();
        }
    
        public string HazardTypeCode { get; set; }
        public string HazardTypeDesc { get; set; }
        public string HazardSignImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EHSSData> EHSSData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSDSDetail> MSDSDetail { get; set; }
    }
}
