//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSDSData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSDSData()
        {
            this.MSDSDetail = new HashSet<MSDSDetail>();
        }
    
        public string EHSSDataID { get; set; }
        public string EmergencyTelephone { get; set; }
        public string HazardStatement { get; set; }
        public string FireStatement { get; set; }
        public string Emergency { get; set; }
        public string StorageDisposal { get; set; }
        public string SpillLeak { get; set; }
        public string AuthorID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string AuditorID { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string MSDSStatus { get; set; }
    
        public virtual EHSSData EHSSData { get; set; }
        public virtual EHSSUser EHSSUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSDSDetail> MSDSDetail { get; set; }
    }
}
