//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSDSDetail
    {
        public string Ingredient { get; set; }
        public string EHSSDataID { get; set; }
        public Nullable<decimal> Ratio { get; set; }
        public string HazardTypeCode { get; set; }
    
        public virtual HazardType HazardType { get; set; }
        public virtual MSDSData MSDSData { get; set; }
    }
}
