//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public string ShipmentID { get; set; }
        public string EHSSDataID { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> DateInProduced { get; set; }
        public Nullable<System.DateTime> DateToPull { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string AddressFrom { get; set; }
        public string ShipperTel { get; set; }
        public string AddressTo { get; set; }
        public string ConsigneeTel { get; set; }
        public string ShippingType { get; set; }
        public string ContainerSize { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public string AuthorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string AuditorID { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ShipmentStatus { get; set; }
    
        public virtual EHSSData EHSSData { get; set; }
        public virtual EHSSUser EHSSUser { get; set; }
    }
}
